### ISSUE TITLE
Compatibility with NeoVim?

### ISSUE THREAD

**Issue by al-the-x** [bfrg/vim-jqplay#5]
This looks like a really handy plugin. It's a great idea!

I use NeoVim vs Vim8, however, and [NeoVim has a different API for job control](https://neovim.io/doc/user/job_control.html) than the [Vim8 API for job control](https://vimhelp.org/channel.txt.html#job-functions-details) you've used. I installed the plugin and tried patching the source to use the different API but couldn't quite get it to work. I'd be happy to hack with you on a version that would work with either.

**Comment by bfrg** [comment]
Sorry but won't fix. I personally don't use Neovim and am not willing to add unnecessary complexity to the plugin.

Neovim is a _separate_ editor that is diverging more and more from Vim. I wish people would finally realize that and start writing separate plugins as well.

Besides, I need to rewrite this plugin anyway (probably from scratch) which will take some time.

**Comment by bfrg** [comment]
Regarding the job APIs, you need to check if Neovim supports reading `stdin` from a buffer. See `:help in_buf`. 

Currently the input json buffer is piped directly to jq through Vim. I don't run anything like `jq '.[]' < file.json`. From the Neovim documentation you linked above it doesn't look like Neovim supports this.

The advantage of using this is that the buffer doesn't have to be written to disk. But there are also caveats, see this [issue](https://github.com/vim/vim/issues/4688).

**Comment by al-the-x** [comment]
> Neovim is a _separate_ editor that is diverging more and more from Vim. I wish people would finally realize that and start writing separate plugins as well.

I've been using vim for more than a decade as my daily driver at this point, infrequently prior to that, and the NeoVim project did some good by reinvigorating development on the main codebase and challenging some of the legacy design decisions.

I think the gross difference between the job control APIs highlights the divergence, though. I haven't been able to find anything public about the decision to diverge from the main project... Or if NeoVim implemented it first or what. I haven't dug into the mailing lists, yet, but those seem like large decisions that should be communicated clearly, especially to plugin developers!

Thanks for the great work on this and the idea. Maybe I'll have a go at a NeoVim version of the plugin based on your advice.

**Comment by phelipetls** [comment]
I just got a working version of this plugin in Neovim at https://github.com/phelipetls/vim-jqplay
